const { test, expect } = require('@playwright/test')

test('Empty checkout form', async ({ page }) => { //VALIDAMOS QUE SI EL FORMULARIO DE CHECKOUT ESTA VACIO NOS MANDE DE REQUERIDO
   await page.goto('https://www.saucedemo.com/')
   await page.locator('[data-test="username"]').click()
   await page.locator('[data-test="username"]').fill('standard_user')
   await page.locator('[data-test="password"]').click()
   await page.locator('[data-test="password"]').fill('secret_sauce')
   await page.locator('[data-test="login-button"]').click()
   await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click()
   await page.locator('[data-test="shopping-cart-link"]').click()
   await page.locator('[data-test="checkout"]').click()
   await page.locator('[data-test="continue"]').click()
   await expect(page.locator('[data-test="error"]')).toBeVisible()
   await expect(page.locator('[data-test="error"]')).toContainText('Error: First Name is required') 
})

test('Success checkout form', async ({ page }) => { //VALIDAMOS LA FUNCIONALIDAD DEL FORMULARIO DEL CHECKOUT
  await page.goto('https://www.saucedemo.com/')
  await page.locator('[data-test="username"]').click()
  await page.locator('[data-test="username"]').fill('standard_user')
  await page.locator('[data-test="password"]').click()
  await page.locator('[data-test="password"]').fill('secret_sauce')
  await page.locator('[data-test="login-button"]').click()
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click()
  await page.locator('[data-test="shopping-cart-link"]').click()
  await page.locator('[data-test="checkout"]').click()
  await page.locator('[data-test="firstName"]').click()
  await page.locator('[data-test="firstName"]').fill('Carla')
  await page.locator('[data-test="lastName"]').click()
  await page.locator('[data-test="lastName"]').fill('Lucero')
  await page.locator('[data-test="postalCode"]').click()
  await page.locator('[data-test="postalCode"]').fill('20126')
  await page.locator('[data-test="continue"]').click()
  await page.locator('[data-test="finish"]').click()
  await expect(page.locator('[data-test="title"]')).toBeVisible()
})